export const Virar_to_dhanu_trains_data = [

  {
    "_id": { "$oid": "660f0001a1b2c3d4e5f60016" },
    "train_no": "09051",
    "departure_time": "01:07",
    "departure_period": "AM",
    "destination": "DAHANU ROAD",
    "train_type": "FAST",
    "origin": "Dadar",
    "via": null,
    "route": "DADAR - BHUSHAVAL",
    "arrives_dahanu": "01:58",
    "platform": "",
    "coaches": "N/A",
    "live_status": null
  },

  {
    "_id": { "$oid": "660f0001a1b2c3d4e5f60017" },
    "train_no": "00001",
    "departure_time": "04:10",
    "departure_period": "AM",
    "destination": "DAHANU ROAD",
    "train_type": "FAST",
    "origin": "VIRAR",
    "via": null,
    "route": "VIRAR - DAHANU ROAD",
    "arrives_dahanu": "05:25",
    "platform": "",
    "coaches": "N/A",
    "live_status": null
  },

  {
    "_id": { "$oid": "660f0001a1b2c3d4e5f60018" },
    "train_no": "19101",
    "departure_time": "04:25",
    "departure_period": "AM",
    "destination": "DAHANU ROAD",
    "train_type": "SLOW",
    "origin": "Virar",
    "via": null,
    "route": "VIRAR-BHARUCH",
    "arrives_dahanu": "05:45",
    "platform": "",
    "coaches": 19,
    "live_status": null
  },
  {
    "_id": { "$oid": "660f0001a1b2c3d4e5f60001" },
    "train_no": "93001",
    "departure_time": "04:50",
    "departure_period": "AM",
    "destination": "DAHANU ROAD",
    "train_type": "SLOW",
    "origin": "VIRAR",
    "via": null,
    "route": "VIRAR - DAHANU ROAD",
    "arrives_dahanu": "06:15",
    "platform": "",
    "coaches": 12,
    "live_status": null
  },

  {
    "_id": { "$oid": "660f0001a1b2c3d4e5f600019" },
    "train_no": "69143",
    "departure_time": "05:15",
    "departure_period": "AM",
    "destination": "DAHANU ROAD",
    "train_type": "SLOW",
    "origin": "VIRAR",
    "via": null,
    "route": "VIRAR - SURAT MEMU",
    "arrives_dahanu": "06:14",
    "platform": "",
    "coaches": 12,
    "live_status": null
  },

  {
    "_id": { "$oid": "660f0001a1b2c3d4e5f60002" },
    "train_no": "93003",
    "departure_time": "05:35",
    "departure_period": "AM",
    "destination": "DAHANU ROAD",
    "train_type": "SLOW",
    "origin": "VIRAR",
    "via": null,
    "route": "VIRAR - DAHANU ROAD",
    "arrives_dahanu": "06:50",
    "platform": "",
    "coaches": 12,
    "live_status": null
  },
  {
    "_id": { "$oid": "660f0001a1b2c3d4e5f60003" },
    "train_no": "93005",
    "departure_time": "06:15",
    "departure_period": "AM",
    "destination": "DAHANU ROAD",
    "train_type": "SLOW",
    "origin": "CHURCHGATE",
    "via": null,
    "route": "CHURCHGATE - DAHANU ROAD",
    "arrives_dahanu": "07:38",
    "platform": "",
    "coaches": 12,
    "live_status": null
  },
  {
    "_id": { "$oid": "660f0001a1b2c3d4e5f60004" },
    "train_no": "93007",
    "departure_time": "07:04",
    "departure_period": "AM",
    "destination": "DAHANU ROAD",
    "train_type": "SLOW",
    "origin": "CHURCHGATE",
    "via": null,
    "route": "CHURCHGATE - DAHANU ROAD",
    "arrives_dahanu": "08:25",
    "platform": "",
    "coaches": 12,
    "live_status": null
  },

  {
    "_id": { "$oid": "660f0001a1b2c3d4e5f600020" },
    "train_no": "69139",
    "departure_time": "07:20",
    "departure_period": "AM",
    "destination": "DAHANU ROAD",
    "train_type": "FAST",
    "origin": "BORIVALI",
    "via": null,
    "route": "BORIVLI - VALSAD MEMU",
    "arrives_dahanu": "08:58",
    "platform": "",
    "coaches": 17,
    "live_status": null
  },

  {
    "_id": { "$oid": "660f0001a1b2c3d4e5f60005" },
    "train_no": "93009",
    "departure_time": "08:29",
    "departure_period": "AM",
    "destination": "DAHANU ROAD",
    "train_type": "SLOW",
    "origin": "CHURCHGATE",
    "via": null,
    "route": "CHURCHGATE - DAHANU ROAD",
    "arrives_dahanu": "09:50",
    "platform": "",
    "coaches": 12,
    "live_status": null
  },
  {
    "_id": { "$oid": "660f0001a1b2c3d4e5f60006" },
    "train_no": "93011",
    "departure_time": "09:01",
    "departure_period": "AM",
    "destination": "DAHANU ROAD",
    "train_type": "SLOW",
    "origin": "CHURCHGATE",
    "via": null,
    "route": "CHURCHGATE - DAHANU ROAD",
    "arrives_dahanu": "10:15",
    "platform": "",
    "coaches": 12,
    "live_status": null
  },
  {
    "_id": { "$oid": "660f0001a1b2c3d4e5f60007" },
    "train_no": "93013",
    "departure_time": "09:30",
    "departure_period": "AM",
    "destination": "DAHANU ROAD",
    "train_type": "SLOW",
    "origin": "VIRAR",
    "via": null,
    "route": "VIRAR - DAHANU ROAD",
    "arrives_dahanu": "10:50",
    "platform": "",
    "coaches": 12,
    "live_status": null
  },
  {
    "_id": { "$oid": "660f0001a1b2c3d4e5f60008" },
    "train_no": "93015",
    "departure_time": "10:07",
    "departure_period": "AM",
    "destination": "DAHANU ROAD",
    "train_type": "SLOW",
    "origin": "CHURCHGATE",
    "via": null,
    "route": "CHURCHGATE - DAHANU ROAD",
    "arrives_dahanu": "11:25",
    "platform": "",
    "coaches": 12,
    "live_status": null
  },

  {
    "_id": { "$oid": "660f0001a1b2c3d4e5f600021" },
    "train_no": "09055",
    "departure_time": "10:06",
    "departure_period": "AM",
    "destination": "DAHANU ROAD",
    "train_type": "FAST",
    "origin": "BANDRA",
    "via": null,
    "route": "BANDRA - SURAT SPL",
    "arrives_dahanu": "11:40",
    "platform": "",
    "coaches": "N/A",
    "live_status": null
  },

  {
    "_id": { "$oid": "660f0001a1b2c3d4e5f600022" },
    "train_no": "19015",
    "departure_time": "10:30",
    "departure_period": "AM",
    "destination": "DAHANU ROAD",
    "train_type": "FAST",
    "origin": "DADAR",
    "via": null,
    "route": "SAURASHTRA EXP",
    "arrives_dahanu": "10:28",
    "platform": "",
    "coaches": 19,
    "live_status": null
  },

  {
    "_id": { "$oid": "660f0001a1b2c3d4e5f600023" },
    "train_no": "59045",
    "departure_time": "11:00",
    "departure_period": "AM",
    "destination": "DAHANU ROAD",
    "train_type": "FAST",
    "origin": "MUMBAI CENTRAL",
    "via": null,
    "route": "MMCT-VAPI PASSANGER",
    "arrives_dahanu": "12:08",
    "platform": "",
    "coaches": 22,
    "live_status": null
  },

  {
    "_id": { "$oid": "660f0001a1b2c3d4e5f60009" },
    "train_no": "93017",
    "departure_time": "11:05",
    "departure_period": "AM",
    "destination": "DAHANU ROAD",
    "train_type": "SLOW",
    "origin": "BORIVALI",
    "via": null,
    "route": "BORIVALI - DAHANU ROAD",
    "arrives_dahanu": "12:20",
    "platform": "",
    "coaches": 12,
    "live_status": null
  },
  {
    "_id": { "$oid": "660f0001a1b2c3d4e5f6000a" },
    "train_no": "93019",
    "departure_time": "11:25",
    "departure_period": "AM",
    "destination": "DAHANU ROAD",
    "train_type": "SLOW",
    "origin": "CHURCHGATE",
    "via": null,
    "route": "CHURCHGATE - DAHANU ROAD",
    "arrives_dahanu": "12:40",
    "platform": "",
    "coaches": 12,
    "live_status": null
  },

  {
    "_id": { "$oid": "660f0001a1b2c3d4e5f600024" },
    "train_no": "59039",
    "departure_time": "11:30",
    "departure_period": "AM",
    "destination": "DAHANU ROAD",
    "train_type": "FAST",
    "origin": "VIRAR",
    "via": null,
    "route": "VIRAR-VALSAD PASSENGER",
    "arrives_dahanu": "12:33",
    "platform": "",
    "coaches": 17,
    "live_status": null
  },

  {
    "_id": { "$oid": "660f0001a1b2c3d4e5f6000b" },
    "train_no": "93021",
    "departure_time": "12:00",
    "departure_period": "PM",
    "destination": "DAHANU ROAD",
    "train_type": "SLOW",
    "origin": "VIRAR",
    "via": null,
    "route": "VIRAR - DAHANU ROAD",
    "arrives_dahanu": "13:34",
    "platform": "",
    "coaches": 12,
    "live_status": null
  },
  {
    "_id": { "$oid": "660f0001a1b2c3d4e5f6000c" },
    "train_no": "93023",
    "departure_time": "12:20",
    "departure_period": "PM",
    "destination": "DAHANU ROAD",
    "train_type": "SLOW",
    "origin": "VIRAR",
    "via": null,
    "route": "VIRAR - DAHANU ROAD",
    "arrives_dahanu": "13:49",
    "platform": "",
    "coaches": 12,
    "live_status": null
  },
  {
    "_id": { "$oid": "660f0001a1b2c3d4e5f6000d" },
    "train_no": "93025",
    "departure_time": "13:20",
    "departure_period": "PM",
    "destination": "DAHANU ROAD",
    "train_type": "SLOW",
    "origin": "VIRAR",
    "via": null,
    "route": "VIRAR - DAHANU ROAD",
    "arrives_dahanu": "14:26",
    "platform": "",
    "coaches": 12,
    "live_status": null
  },

  {
    "_id": { "$oid": "660f0001a1b2c3d4e5f600025" },
    "train_no": "19417",
    "departure_time": "13:55",
    "departure_period": "PM",
    "destination": "DAHANU ROAD",
    "train_type": "FAST",
    "origin": "BORIVALI",
    "via": null,
    "route": "BORIVALI-AHMEDABAD EXPRESS",
    "arrives_dahanu": "15:38",
    "platform": "",
    "coaches": 14,
    "live_status": null
  },

  {
    "_id": { "$oid": "660f0001a1b2c3d4e5f6000e" },
    "train_no": "93027",
    "departure_time": "15:00",
    "departure_period": "PM",
    "destination": "DAHANU ROAD",
    "train_type": "SLOW",
    "origin": "VIRAR",
    "via": null,
    "route": "VIRAR - DAHANU ROAD",
    "arrives_dahanu": "16:20",
    "platform": "",
    "coaches": 12,
    "live_status": null
  },
  {
    "_id": { "$oid": "660f0001a1b2c3d4e5f6000f" },
    "train_no": "93029",
    "departure_time": "15:45",
    "departure_period": "PM",
    "destination": "DAHANU ROAD",
    "train_type": "SLOW",
    "origin": "VIRAR",
    "via": null,
    "route": "VIRAR - DAHANU ROAD",
    "arrives_dahanu": "17:08",
    "platform": "",
    "coaches": 12,
    "live_status": null
  },
  {
    "_id": { "$oid": "660f0001a1b2c3d4e5f60010" },
    "train_no": "93031",
    "departure_time": "16:29",
    "departure_period": "PM",
    "destination": "DAHANU ROAD",
    "train_type": "SLOW",
    "origin": "CHURCHGATE",
    "via": null,
    "route": "CHURCHGATE - DAHANU ROAD",
    "arrives_dahanu": "18:00",
    "platform": "",
    "coaches": 12,
    "live_status": null
  },

  {
    "_id": { "$oid": "660f0001a1b2c3d4e5f600026" },
    "train_no": "19001",
    "departure_time": "17:00",
    "departure_period": "PM",
    "destination": "DAHANU ROAD",
    "train_type": "FAST",
    "origin": "VIRAR",
    "via": null,
    "route": "VIRAR-SURAT EXPRESS",
    "arrives_dahanu": "18:03",
    "platform": "",
    "coaches": 21,
    "live_status": null
  },

  {
    "_id": { "$oid": "660f0001a1b2c3d4e5f60011" },
    "train_no": "93033",
    "departure_time": "18:18",
    "departure_period": "PM",
    "destination": "DAHANU ROAD",
    "train_type": "SLOW",
    "origin": "VIRAR",
    "via": null,
    "route": "VIRAR - DAHANU ROAD",
    "arrives_dahanu": "19:30",
    "platform": "",
    "coaches": 12,
    "live_status": null
  },
  {
    "_id": { "$oid": "660f0001a1b2c3d4e5f60012" },
    "train_no": "93035",
    "departure_time": "19:07",
    "departure_period": "PM",
    "destination": "DAHANU ROAD",
    "train_type": "SLOW",
    "origin": "DADAR",
    "via": null,
    "route": "DADAR - DAHANU ROAD",
    "arrives_dahanu": "20:20",
    "platform": "",
    "coaches": 12,
    "live_status": null
  },

  {
    "_id": { "$oid": "660f0001a1b2c3d4e5f600027" },
    "train_no": "59023",
    "departure_time": "19:10",
    "departure_period": "PM",
    "destination": "DAHANU ROAD",
    "train_type": "FAST",
    "origin": "MUMBAI CENTRAL",
    "via": null,
    "route": "MUMBAI CETRAL-VALSAD PASSENGER",
    "arrives_dahanu": "20:38",
    "platform": "",
    "coaches": 22,
    "live_status": null
  },

  {
    "_id": { "$oid": "660f0001a1b2c3d4e5f60013" },
    "train_no": "93037",
    "departure_time": "20:30",
    "departure_period": "PM",
    "destination": "DAHANU ROAD",
    "train_type": "SLOW",
    "origin": "VIRAR",
    "via": null,
    "route": "VIRAR - DAHANU ROAD",
    "arrives_dahanu": "21:55",
    "platform": "",
    "coaches": 12,
    "live_status": null
  },

  {
    "_id": { "$oid": "660f0001a1b2c3d4e5f600028" },
    "train_no": "22927",
    "departure_time": "20:45",
    "departure_period": "PM",
    "destination": "DAHANU ROAD",
    "train_type": "FAST",
    "origin": "BANDRA",
    "via": null,
    "route": "LOKSHAKTI EXP",
    "arrives_dahanu": "21:53",
    "platform": "",
    "coaches": 22,
    "live_status": null
  },

  {
    "_id": { "$oid": "660f0001a1b2c3d4e5f600029" },
    "train_no": "69161",
    "departure_time": "21:00",
    "departure_period": "PM",
    "destination": "DAHANU ROAD",
    "train_type": "SLOW",
    "origin": "PANVEL",
    "via": null,
    "route": "PANVEL-DAHANU MEMU",
    "arrives_dahanu": "22:32",
    "platform": "",
    "coaches": 10,
    "live_status": null
  },

  {
    "_id": { "$oid": "660f0001a1b2c3d4e5f60014" },
    "train_no": "93039",
    "departure_time": "21:05",
    "departure_period": "PM",
    "destination": "DAHANU ROAD",
    "train_type": "SLOW",
    "origin": "VIRAR",
    "via": null,
    "route": "VIRAR - DAHANU ROAD",
    "arrives_dahanu": "22:16",
    "platform": "",
    "coaches": 12,
    "live_status": null
  },
  {
    "_id": { "$oid": "660f0001a1b2c3d4e5f60015" },
    "train_no": "93041",
    "departure_time": "21:41",
    "departure_period": "PM",
    "destination": "DAHANU ROAD",
    "train_type": "SLOW",
    "origin": "CHURCHGATE",
    "via": null,
    "route": "CHURCHGATE - DAHANU ROAD",
    "arrives_dahanu": "23:05",
    "platform": "",
    "coaches": 12,
    "live_status": null
  },

  {
    "_id": { "$oid": "660f0001a1b2c3d4e5f600030" },
    "train_no": "69173",
    "departure_time": "22:50",
    "departure_period": "PM",
    "destination": "DAHANU ROAD",
    "train_type": "FAST",
    "origin": "VIRAR",
    "via": null,
    "route": "VIRAR-DAHANU MEMU",
    "arrives_dahanu": "00:15",
    "platform": "",
    "coaches": 20,
    "live_status": null
  },

  {
    "_id": { "$oid": "660f0001a1b2c3d4e5f600031" },
    "train_no": "19425",
    "departure_time": "23:20",
    "departure_period": "PM",
    "destination": "DAHANU ROAD",
    "train_type": "FAST",
    "origin": "BORIVALI",
    "via": null,
    "route": "MMCT-NANDURBAR EXP",
    "arrives_dahanu": "00:57",
    "platform": "",
    "coaches": 15,
    "live_status": null
  },

];